# -*- coding: utf-8 -*-
"""desempenhoConsultoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVR4EnoZj9YGU5ALfsZurRYXOaYPx3Lf

# Importando base de dados
"""

import pandas as pd
import plotly.express as px

tabela = pd.read_excel("dados_consultoria.xlsx")
display(tabela)

"""- desempenho de consultores por região."""

desempenho_consultores = tabela.groupby(["Consultor", "Região"])["Valor da Venda (R$)"].sum()
for consultor in tabela["Consultor"].unique():
  display(desempenho_consultores.loc[[consultor]].reset_index())

"""- Gráfico de Desempenho por Região"""

fig = px.bar(desempenho_consultores.reset_index(), x="Consultor", y="Valor da Venda (R$)", color="Região", barmode="group")
fig.show()

"""- consultores com **maior e menor performance**"""

total_venda_consultor = tabela.groupby(["Consultor"])["Valor da Venda (R$)"].sum()
total_venda_consultor = total_venda_consultor.rename("Total Vendido")
total_venda_consultor = total_venda_consultor.reset_index()

display(total_venda_consultor)

maior_desempenho = total_venda_consultor[total_venda_consultor["Total Vendido"] == total_venda_consultor["Total Vendido"].max()]
maior_desempenho = maior_desempenho.rename(columns={"Total Vendido": "Maior Desempenho"})
display(maior_desempenho)

menor_desempenho = total_venda_consultor[total_venda_consultor["Total Vendido"] == total_venda_consultor["Total Vendido"].min()]
menor_desempenho = menor_desempenho.rename(columns={"Total Vendido": "Menor Desempenho"})
display(menor_desempenho)

grafico_performace = px.bar(total_venda_consultor, x="Consultor", y="Total Vendido")
grafico_performace.show()

"""# Calculo dos **KPIs**

- Total de vendas por consultor
"""

qtd_vendas_consultor = tabela.groupby(["Consultor"])["ID do Cliente"].count()
qtd_vendas_consultor = qtd_vendas_consultor.rename("Quantidade de Vendas")
display(qtd_vendas_consultor.reset_index())

display(total_venda_consultor)

"""- Ticket Médio por Cliente"""

# Calcular o ticket médio geral por cliente
ticket_medio = tabela["Valor da Venda (R$)"].sum() / tabela["ID do Cliente"].nunique()

# Exibir o resultado formatado
print(f"Ticket médio por cliente: R$ {ticket_medio:,.2f}")

"""   - Quantidade de clientes atendidos por mês."""

# Converter a data e extrair o mês (nome)
tabela["Mês"] = pd.to_datetime(tabela["Data da Venda"]).dt.strftime("%B")

# Agrupar por mês e contar clientes únicos
total_cliente_por_mes = tabela.groupby("Mês")["ID do Cliente"].nunique().reset_index()

# Renomear coluna
total_cliente_por_mes.columns = ["Mês", "Total de Clientes"]

# Exibir
display(total_cliente_por_mes)

grafico_total_cliente = px.bar(total_cliente_por_mes, x="Mês", y="Total de Clientes", title="Total de Clientes por Mês")
grafico_total_cliente.show()